manifest:
  remotes:
    - name: achan231
      url-base: https://github.com/achan231
  projects:
    - name: zmk-alextesting
      remote: achan231
      revision: main
      import: app/west.yml
  self:
    path: config
